version: '3'
services:
  library-service:
    build: .
    hostname: rest.library.local
    volumes:
      - ./app:/var/www/html/app
      - ./src:/var/www/html/src
      - ./data:/var/www/html/data
      - ./index.php:/var/www/html/index.php
    ports:
      - 80:80